name = "Create: Ночная смена"
author = "Georgij"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "400330c2c51303f176d2dfdcbf6ca8a79263f9c401357958967cd24be629eebf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
