name = "Create: Ночная смена"
author = "Georgij"
version = "2.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "677bcd4f3765985e8dcc5c5f136eee1dae67a83012fbf506a5010f5bd39a7351"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
