name = "Create: Ночная смена"
author = "Georgij"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef9f36464d9dd157e3eec3597aa82d2abc181ec17828e8e05d46b6e9435bcb98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
