// ==========================================================================
// «Вахта» — рецепты-обходы ручного крафта (docs/VAHTA.md, решения 2, 4, 5).
// Все удаления — по id (event.remove({ id })), без фильтров по output/input: так не запускается
// параллельный скан всех рецептов, и список проверяем глазами. Списки собраны по
// tools/data/recipes-dump.json.gz, подробности и полный разбор — docs/VAHTA-RULES.md.
// ==========================================================================

// ---------- п.3. карманные верстаки и обходы ----------
var NS_VAHTA_POCKET_IDS = [
	// Sophisticated Backpacks / Storage: апгрейд крафта (сетка 3×3 прямо в рюкзаке/сундуке)
	'sophisticatedbackpacks:crafting_upgrade',
	'sophisticatedstorage:crafting_upgrade',
	'sophisticatedstorage:backpack_crafting_upgrade_from_storage_crafting_upgrade',
	'sophisticatedstorage:storage_crafting_upgrade_from_backpack_crafting_upgrade',
	// апгрейд камнереза (ручная резка; на вахте камень режет пила — allowStonecuttingOnSaw)
	'sophisticatedbackpacks:stonecutter_upgrade',
	'sophisticatedstorage:stonecutter_upgrade',
	'sophisticatedstorage:backpack_stonecutter_upgrade_from_storage_stonecutter_upgrade',
	'sophisticatedstorage:storage_stonecutter_upgrade_from_backpack_stonecutter_upgrade',
	// апгрейды-«верстаки» Chipped: мода Chipped в сборке нет, рецепты под условием mod_loaded —
	// удаляем на будущее, если мод добавят (удаление несуществующего id безвредно)
	'sophisticatedbackpacks:chipped/alchemy_bench_upgrade',
	'sophisticatedbackpacks:chipped/botanist_workbench_upgrade',
	'sophisticatedbackpacks:chipped/carpenters_table_upgrade',
	'sophisticatedbackpacks:chipped/glassblower_upgrade',
	'sophisticatedbackpacks:chipped/loom_table_upgrade',
	'sophisticatedbackpacks:chipped/mason_table_upgrade',
	'sophisticatedbackpacks:chipped/tinkering_table_upgrade',
	'sophisticatedstorage:chipped/alchemy_bench_upgrade',
	'sophisticatedstorage:chipped/botanist_workbench_upgrade',
	'sophisticatedstorage:chipped/carpenters_table_upgrade',
	'sophisticatedstorage:chipped/glassblower_upgrade',
	'sophisticatedstorage:chipped/loom_table_upgrade',
	'sophisticatedstorage:chipped/mason_table_upgrade',
	'sophisticatedstorage:chipped/tinkering_table_upgrade',
	'sophisticatedstorage:backpack_chipped_alchemy_bench_upgrade_from_storage_chipped_alchemy_bench_upgrade',
	'sophisticatedstorage:backpack_chipped_botanist_workbench_upgrade_from_storage_chipped_botanist_workbench_upgrade',
	'sophisticatedstorage:backpack_chipped_carpenters_table_upgrade_from_storage_chipped_carpenters_table_upgrade',
	'sophisticatedstorage:backpack_chipped_glassblower_upgrade_from_storage_chipped_glassblower_upgrade',
	'sophisticatedstorage:backpack_chipped_loom_table_upgrade_from_storage_chipped_loom_table_upgrade',
	'sophisticatedstorage:backpack_chipped_mason_table_upgrade_from_storage_chipped_mason_table_upgrade',
	'sophisticatedstorage:backpack_chipped_tinkering_table_upgrade_from_storage_chipped_tinkering_table_upgrade',
	'sophisticatedstorage:storage_chipped_alchemy_bench_upgrade_from_backpack_chipped_alchemy_bench_upgrade',
	'sophisticatedstorage:storage_chipped_botanist_workbench_upgrade_from_backpack_chipped_botanist_workbench_upgrade',
	'sophisticatedstorage:storage_chipped_carpenters_table_upgrade_from_backpack_chipped_carpenters_table_upgrade',
	'sophisticatedstorage:storage_chipped_glassblower_upgrade_from_backpack_chipped_glassblower_upgrade',
	'sophisticatedstorage:storage_chipped_loom_table_upgrade_from_backpack_chipped_loom_table_upgrade',
	'sophisticatedstorage:storage_chipped_mason_table_upgrade_from_backpack_chipped_mason_table_upgrade',
	'sophisticatedstorage:storage_chipped_tinkering_table_upgrade_from_backpack_chipped_tinkering_table_upgrade',
	// Create: чертёж крафта — повешенный на стену, крафтит ПКМ прямо из инвентаря
	'create:crafting/appliances/crafting_blueprint',
	// ванильный крафтер: окно 3×3 + импульс редстоуна = верстак без механизмов Create
	// (окно у найденных в мире крафтеров закрыто в 10_no_hand_crafting.js)
	'minecraft:crafter',
]

// ---------- п.4. печь руду не плавит ----------
// smelting/blasting, где вход — руда, сырая руда или блок руды. Дробленую руду Create
// (create:crushed_raw_*) НЕ трогаем: вентилятор (bulk smelting/blasting) плавит её по этим же
// типам рецептов. Путь: руда → дробилка → (промывка) → вентилятор/печь.
// Модовых «печей» с рудой на входе в дампе нет (проверены все типы; руда встречается ещё только
// в машинах: create:cutting сырых алмаза/изумруда COE, dndesires:seething, northstar:engraving).
var NS_VAHTA_ORE_SMELT_IDS = [
	// cgs (6)
	'cgs:lead_ingot_from_blasting_deepslate_lead_ore',
	'cgs:lead_ingot_from_blasting_lead_ore',
	'cgs:lead_ingot_from_blasting_raw_lead',
	'cgs:lead_ingot_from_smelting_deepslate_lead_ore',
	'cgs:lead_ingot_from_smelting_lead_ore',
	'cgs:lead_ingot_from_smelting_raw_lead',
	// create (4)
	'create:blasting/zinc_ingot_from_ore',
	'create:blasting/zinc_ingot_from_raw_ore',
	'create:smelting/zinc_ingot_from_ore',
	'create:smelting/zinc_ingot_from_raw_ore',
	// createpropulsion (5)
	'createpropulsion:blasting/platinum_ingot_from_deepslate_platinum_ore',
	'createpropulsion:blasting/platinum_ingot_from_platinum_ore',
	'createpropulsion:smelting/platinum_ingot_from_deepslate_platinum_ore',
	'createpropulsion:smelting/platinum_ingot_from_platinum_ore',
	'createpropulsion:smelting/platinum_ingot_from_raw_platinum',
	// minecraft (42)
	'minecraft:coal_from_blasting_coal_ore',
	'minecraft:coal_from_blasting_deepslate_coal_ore',
	'minecraft:coal_from_smelting_coal_ore',
	'minecraft:coal_from_smelting_deepslate_coal_ore',
	'minecraft:copper_ingot_from_blasting_copper_ore',
	'minecraft:copper_ingot_from_blasting_deepslate_copper_ore',
	'minecraft:copper_ingot_from_blasting_raw_copper',
	'minecraft:copper_ingot_from_smelting_copper_ore',
	'minecraft:copper_ingot_from_smelting_deepslate_copper_ore',
	'minecraft:copper_ingot_from_smelting_raw_copper',
	'minecraft:diamond_from_blasting_deepslate_diamond_ore',
	'minecraft:diamond_from_blasting_diamond_ore',
	'minecraft:diamond_from_smelting_deepslate_diamond_ore',
	'minecraft:diamond_from_smelting_diamond_ore',
	'minecraft:emerald_from_blasting_deepslate_emerald_ore',
	'minecraft:emerald_from_blasting_emerald_ore',
	'minecraft:emerald_from_smelting_deepslate_emerald_ore',
	'minecraft:emerald_from_smelting_emerald_ore',
	'minecraft:gold_ingot_from_blasting_deepslate_gold_ore',
	'minecraft:gold_ingot_from_blasting_gold_ore',
	'minecraft:gold_ingot_from_blasting_nether_gold_ore',
	'minecraft:gold_ingot_from_blasting_raw_gold',
	'minecraft:gold_ingot_from_smelting_deepslate_gold_ore',
	'minecraft:gold_ingot_from_smelting_gold_ore',
	'minecraft:gold_ingot_from_smelting_nether_gold_ore',
	'minecraft:gold_ingot_from_smelting_raw_gold',
	'minecraft:iron_ingot_from_blasting_deepslate_iron_ore',
	'minecraft:iron_ingot_from_blasting_iron_ore',
	'minecraft:iron_ingot_from_blasting_raw_iron',
	'minecraft:iron_ingot_from_smelting_deepslate_iron_ore',
	'minecraft:iron_ingot_from_smelting_iron_ore',
	'minecraft:iron_ingot_from_smelting_raw_iron',
	'minecraft:lapis_lazuli_from_blasting_deepslate_lapis_ore',
	'minecraft:lapis_lazuli_from_blasting_lapis_ore',
	'minecraft:lapis_lazuli_from_smelting_deepslate_lapis_ore',
	'minecraft:lapis_lazuli_from_smelting_lapis_ore',
	'minecraft:quartz',
	'minecraft:quartz_from_blasting',
	'minecraft:redstone_from_blasting_deepslate_redstone_ore',
	'minecraft:redstone_from_blasting_redstone_ore',
	'minecraft:redstone_from_smelting_deepslate_redstone_ore',
	'minecraft:redstone_from_smelting_redstone_ore',
	// northstar (152)
	'northstar:blasting/iron_ingot_from_martian_ore',
	'northstar:blasting/mars_copper_ore',
	'northstar:blasting/mars_deep_copper_ore',
	'northstar:blasting/mars_deep_diamond_ore',
	'northstar:blasting/mars_deep_gold_ore',
	'northstar:blasting/mars_deep_iron_ore',
	'northstar:blasting/mars_deep_quartz_ore',
	'northstar:blasting/mars_deep_redstone_ore',
	'northstar:blasting/mars_deep_titanium_ore',
	'northstar:blasting/mars_deep_zinc_ore',
	'northstar:blasting/mars_diamond_ore',
	'northstar:blasting/mars_gold_ore',
	'northstar:blasting/mars_iron_ore',
	'northstar:blasting/mars_quartz_ore',
	'northstar:blasting/mars_redstone_ore',
	'northstar:blasting/mars_titanium_ore',
	'northstar:blasting/mars_zinc_ore',
	'northstar:blasting/mercury_copper_ore',
	'northstar:blasting/mercury_deep_copper_ore',
	'northstar:blasting/mercury_deep_diamond_ore',
	'northstar:blasting/mercury_deep_glowstone_ore',
	'northstar:blasting/mercury_deep_gold_ore',
	'northstar:blasting/mercury_deep_iron_ore',
	'northstar:blasting/mercury_deep_lapis_ore',
	'northstar:blasting/mercury_deep_redstone_ore',
	'northstar:blasting/mercury_deep_titanium_ore',
	'northstar:blasting/mercury_deep_tungsten_ore',
	'northstar:blasting/mercury_deep_zinc_ore',
	'northstar:blasting/mercury_diamond_ore',
	'northstar:blasting/mercury_glowstone_ore',
	'northstar:blasting/mercury_gold_ore',
	'northstar:blasting/mercury_iron_ore',
	'northstar:blasting/mercury_lapis_ore',
	'northstar:blasting/mercury_redstone_ore',
	'northstar:blasting/mercury_titanium_ore',
	'northstar:blasting/mercury_tungsten_ore',
	'northstar:blasting/mercury_zinc_ore',
	'northstar:blasting/moon_copper_ore',
	'northstar:blasting/moon_deep_copper_ore',
	'northstar:blasting/moon_deep_diamond_ore',
	'northstar:blasting/moon_deep_glowstone_ore',
	'northstar:blasting/moon_deep_gold_ore',
	'northstar:blasting/moon_deep_iron_ore',
	'northstar:blasting/moon_deep_lapis_ore',
	'northstar:blasting/moon_deep_redstone_ore',
	'northstar:blasting/moon_deep_titanium_ore',
	'northstar:blasting/moon_deep_zinc_ore',
	'northstar:blasting/moon_diamond_ore',
	'northstar:blasting/moon_glowstone_ore',
	'northstar:blasting/moon_gold_ore',
	'northstar:blasting/moon_iron_ore',
	'northstar:blasting/moon_lapis_ore',
	'northstar:blasting/moon_redstone_ore',
	'northstar:blasting/moon_titanium_ore',
	'northstar:blasting/moon_zinc_ore',
	'northstar:blasting/titanium_ingot_from_raw',
	'northstar:blasting/tungsten_ingot_from_raw',
	'northstar:blasting/venus_coal_ore',
	'northstar:blasting/venus_copper_ore',
	'northstar:blasting/venus_deep_copper_ore',
	'northstar:blasting/venus_deep_diamond_ore',
	'northstar:blasting/venus_deep_glowstone_ore',
	'northstar:blasting/venus_deep_gold_ore',
	'northstar:blasting/venus_deep_iron_ore',
	'northstar:blasting/venus_deep_quartz_ore',
	'northstar:blasting/venus_deep_redstone_ore',
	'northstar:blasting/venus_deep_titanium_ore',
	'northstar:blasting/venus_deep_zinc_ore',
	'northstar:blasting/venus_diamond_ore',
	'northstar:blasting/venus_glowstone_ore',
	'northstar:blasting/venus_gold_ore',
	'northstar:blasting/venus_iron_ore',
	'northstar:blasting/venus_quartz_ore',
	'northstar:blasting/venus_redstone_ore',
	'northstar:blasting/venus_titanium_ore',
	'northstar:blasting/venus_zinc_ore',
	'northstar:smelting/iron_ingot_from_martian_ore',
	'northstar:smelting/mars_copper_ore',
	'northstar:smelting/mars_deep_copper_ore',
	'northstar:smelting/mars_deep_diamond_ore',
	'northstar:smelting/mars_deep_gold_ore',
	'northstar:smelting/mars_deep_iron_ore',
	'northstar:smelting/mars_deep_quartz_ore',
	'northstar:smelting/mars_deep_redstone_ore',
	'northstar:smelting/mars_deep_titanium_ore',
	'northstar:smelting/mars_deep_zinc_ore',
	'northstar:smelting/mars_diamond_ore',
	'northstar:smelting/mars_gold_ore',
	'northstar:smelting/mars_iron_ore',
	'northstar:smelting/mars_quartz_ore',
	'northstar:smelting/mars_redstone_ore',
	'northstar:smelting/mars_titanium_ore',
	'northstar:smelting/mars_zinc_ore',
	'northstar:smelting/mercury_copper_ore',
	'northstar:smelting/mercury_deep_copper_ore',
	'northstar:smelting/mercury_deep_diamond_ore',
	'northstar:smelting/mercury_deep_glowstone_ore',
	'northstar:smelting/mercury_deep_gold_ore',
	'northstar:smelting/mercury_deep_iron_ore',
	'northstar:smelting/mercury_deep_lapis_ore',
	'northstar:smelting/mercury_deep_redstone_ore',
	'northstar:smelting/mercury_deep_titanium_ore',
	'northstar:smelting/mercury_deep_tungsten_ore',
	'northstar:smelting/mercury_deep_zinc_ore',
	'northstar:smelting/mercury_diamond_ore',
	'northstar:smelting/mercury_glowstone_ore',
	'northstar:smelting/mercury_gold_ore',
	'northstar:smelting/mercury_iron_ore',
	'northstar:smelting/mercury_lapis_ore',
	'northstar:smelting/mercury_redstone_ore',
	'northstar:smelting/mercury_titanium_ore',
	'northstar:smelting/mercury_tungsten_ore',
	'northstar:smelting/mercury_zinc_ore',
	'northstar:smelting/moon_copper_ore',
	'northstar:smelting/moon_deep_copper_ore',
	'northstar:smelting/moon_deep_diamond_ore',
	'northstar:smelting/moon_deep_glowstone_ore',
	'northstar:smelting/moon_deep_gold_ore',
	'northstar:smelting/moon_deep_iron_ore',
	'northstar:smelting/moon_deep_lapis_ore',
	'northstar:smelting/moon_deep_redstone_ore',
	'northstar:smelting/moon_deep_titanium_ore',
	'northstar:smelting/moon_deep_zinc_ore',
	'northstar:smelting/moon_diamond_ore',
	'northstar:smelting/moon_glowstone_ore',
	'northstar:smelting/moon_gold_ore',
	'northstar:smelting/moon_iron_ore',
	'northstar:smelting/moon_lapis_ore',
	'northstar:smelting/moon_redstone_ore',
	'northstar:smelting/moon_titanium_ore',
	'northstar:smelting/moon_zinc_ore',
	'northstar:smelting/titanium_ingot_from_raw',
	'northstar:smelting/tungsten_ingot_from_raw',
	'northstar:smelting/venus_coal_ore',
	'northstar:smelting/venus_copper_ore',
	'northstar:smelting/venus_deep_copper_ore',
	'northstar:smelting/venus_deep_diamond_ore',
	'northstar:smelting/venus_deep_glowstone_ore',
	'northstar:smelting/venus_deep_gold_ore',
	'northstar:smelting/venus_deep_iron_ore',
	'northstar:smelting/venus_deep_quartz_ore',
	'northstar:smelting/venus_deep_redstone_ore',
	'northstar:smelting/venus_deep_titanium_ore',
	'northstar:smelting/venus_deep_zinc_ore',
	'northstar:smelting/venus_diamond_ore',
	'northstar:smelting/venus_glowstone_ore',
	'northstar:smelting/venus_gold_ore',
	'northstar:smelting/venus_iron_ore',
	'northstar:smelting/venus_quartz_ore',
	'northstar:smelting/venus_redstone_ore',
	'northstar:smelting/venus_titanium_ore',
	'northstar:smelting/venus_zinc_ore',
	// tfmg (9)
	'tfmg:blasting/lead_ingot_blasting',
	'tfmg:blasting/lithium_ingot_blasting',
	'tfmg:blasting/nickel_ingot_blasting',
	'tfmg:smelting/lead_ingot',
	'tfmg:smelting/lead_ingot_blasting',
	'tfmg:smelting/lithium_ingot',
	'tfmg:smelting/lithium_ingot_blasting',
	'tfmg:smelting/nickel_ingot',
	'tfmg:smelting/nickel_ingot_blasting',
]

// ---------- п.5. доски — только пилой, палки — пилой по доскам ----------
// рецепты верстака «бревно/древесина/стебель/блок бамбука → доски»
var NS_VAHTA_PLANK_IDS = [
	'minecraft:oak_planks',
	'minecraft:spruce_planks',
	'minecraft:birch_planks',
	'minecraft:jungle_planks',
	'minecraft:acacia_planks',
	'minecraft:dark_oak_planks',
	'minecraft:mangrove_planks',
	'minecraft:cherry_planks',
	'minecraft:crimson_planks',
	'minecraft:warped_planks',
	'minecraft:bamboo_planks',
	'northstar:argyre_planks',
	'northstar:calorian_planks',
	'northstar:coiler_planks',
	'northstar:wilter_planks',
	'garnished:wood/nut/nut_planks',
	'garnished:wood/sepia/sepia_planks',
	// «доски → палки» (#minecraft:planks ×2 → 4 палки). Бамбук → палка оставлен (не доски).
	'minecraft:stick',
]

// Create 6.0.10 не везёт рецептов пилы для ванильных брёвен (в jar: только andesite_alloy,
// bamboo_planks и compat для чужих модов) — добавляем сами: бревно → окорённое → 6 досок
// (бамбук: блок → окорённый → 3 доски). Уже существующие рецепты Garnished не дублируем.
// [вход, выход, количество]
var NS_VAHTA_CUTTING = [
	['minecraft:oak_log', 'minecraft:stripped_oak_log', 1],
	['minecraft:oak_wood', 'minecraft:stripped_oak_wood', 1],
	['minecraft:spruce_log', 'minecraft:stripped_spruce_log', 1],
	['minecraft:spruce_wood', 'minecraft:stripped_spruce_wood', 1],
	['minecraft:birch_log', 'minecraft:stripped_birch_log', 1],
	['minecraft:birch_wood', 'minecraft:stripped_birch_wood', 1],
	['minecraft:jungle_log', 'minecraft:stripped_jungle_log', 1],
	['minecraft:jungle_wood', 'minecraft:stripped_jungle_wood', 1],
	['minecraft:acacia_log', 'minecraft:stripped_acacia_log', 1],
	['minecraft:acacia_wood', 'minecraft:stripped_acacia_wood', 1],
	['minecraft:dark_oak_log', 'minecraft:stripped_dark_oak_log', 1],
	['minecraft:dark_oak_wood', 'minecraft:stripped_dark_oak_wood', 1],
	['minecraft:mangrove_log', 'minecraft:stripped_mangrove_log', 1],
	['minecraft:mangrove_wood', 'minecraft:stripped_mangrove_wood', 1],
	['minecraft:cherry_log', 'minecraft:stripped_cherry_log', 1],
	['minecraft:cherry_wood', 'minecraft:stripped_cherry_wood', 1],
	['minecraft:crimson_stem', 'minecraft:stripped_crimson_stem', 1],
	['minecraft:crimson_hyphae', 'minecraft:stripped_crimson_hyphae', 1],
	['minecraft:warped_stem', 'minecraft:stripped_warped_stem', 1],
	['minecraft:warped_hyphae', 'minecraft:stripped_warped_hyphae', 1],
	['minecraft:bamboo_block', 'minecraft:stripped_bamboo_block', 1],
	['northstar:argyre_log', 'northstar:stripped_argyre_log', 1],
	['northstar:coiler_log', 'northstar:stripped_coiler_log', 1],
	['northstar:wilter_log', 'northstar:stripped_wilter_log', 1],
	['minecraft:stripped_oak_log', 'minecraft:oak_planks', 6],
	['minecraft:stripped_oak_wood', 'minecraft:oak_planks', 6],
	['minecraft:stripped_spruce_log', 'minecraft:spruce_planks', 6],
	['minecraft:stripped_spruce_wood', 'minecraft:spruce_planks', 6],
	['minecraft:stripped_birch_log', 'minecraft:birch_planks', 6],
	['minecraft:stripped_birch_wood', 'minecraft:birch_planks', 6],
	['minecraft:stripped_jungle_log', 'minecraft:jungle_planks', 6],
	['minecraft:stripped_jungle_wood', 'minecraft:jungle_planks', 6],
	['minecraft:stripped_acacia_log', 'minecraft:acacia_planks', 6],
	['minecraft:stripped_acacia_wood', 'minecraft:acacia_planks', 6],
	['minecraft:stripped_dark_oak_log', 'minecraft:dark_oak_planks', 6],
	['minecraft:stripped_dark_oak_wood', 'minecraft:dark_oak_planks', 6],
	['minecraft:stripped_mangrove_log', 'minecraft:mangrove_planks', 6],
	['minecraft:stripped_mangrove_wood', 'minecraft:mangrove_planks', 6],
	['minecraft:stripped_cherry_log', 'minecraft:cherry_planks', 6],
	['minecraft:stripped_cherry_wood', 'minecraft:cherry_planks', 6],
	['minecraft:stripped_crimson_stem', 'minecraft:crimson_planks', 6],
	['minecraft:stripped_crimson_hyphae', 'minecraft:crimson_planks', 6],
	['minecraft:stripped_warped_stem', 'minecraft:warped_planks', 6],
	['minecraft:stripped_warped_hyphae', 'minecraft:warped_planks', 6],
	['minecraft:stripped_bamboo_block', 'minecraft:bamboo_planks', 3],
	['northstar:stripped_argyre_log', 'northstar:argyre_planks', 6],
	['northstar:stripped_coiler_log', 'northstar:coiler_planks', 6],
	['northstar:stripped_wilter_log', 'northstar:wilter_planks', 6],
	['northstar:calorian_log', 'northstar:calorian_planks', 6],
	['garnished:stripped_nut_wood', 'garnished:nut_planks', 6],
	['garnished:stripped_sepia_hyphae', 'garnished:sepia_planks', 6],
]

ServerEvents.recipes(event => {
	var lists = [NS_VAHTA_POCKET_IDS, NS_VAHTA_ORE_SMELT_IDS, NS_VAHTA_PLANK_IDS]
	for (var l = 0; l < lists.length; l++) {
		for (var i = 0; i < lists[l].length; i++) event.remove({ id: lists[l][i] })
	}

	for (var c = 0; c < NS_VAHTA_CUTTING.length; c++) {
		var r = NS_VAHTA_CUTTING[c]
		var name = r[0].replace(':', '/')
		event.recipes.create.cutting(r[2] + 'x ' + r[1], [r[0]]).id('nightshift:vahta/cutting/' + name)
	}
	// палки: 1 доска → 2 палки (как у верстака: 2 доски → 4)
	event.recipes.create.cutting('2x minecraft:stick', nsIngs(['#minecraft:planks'])).id('nightshift:vahta/cutting/planks_to_sticks')
})
